apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: subsurface-management-storybook
spec:
  environments:
    - name: production
      build:
        from: main

  components:
    - name: client
      src: ./
      ports:
        - name: https
          port: 8080
      publicPort: https

  dnsAppAlias:
    environment: production
    component: client
